import { execSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';

const UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36";
const families = {
  Anton: "Anton",
  ArchivoBlack: "Archivo+Black",
  BarlowCondensed: "Barlow+Condensed:wght@400;500;600;700",
  SpecialElite: "Special+Elite",
  PermanentMarker: "Permanent+Marker",
};

let out = "/* Self-hosted fonts — generated by build-fonts.mjs */\n";
for (const [name, fam] of Object.entries(families)) {
  const css = execSync(`curl -sS -A "${UA}" "https://fonts.googleapis.com/css2?family=${fam}&display=swap"`).toString();
  // split into @font-face blocks
  const blocks = css.split('@font-face').slice(1);
  let i = 0;
  for (const b of blocks) {
    const url = b.match(/url\((https:[^)]+\.woff2)\)/);
    if (!url) continue;
    const file = `assets/fonts/${name}_${i}.woff2`;
    // download
    execSync(`curl -sS -o "${file}" "${url[1]}"`);
    // rebuild the @font-face block with local url
    let block = ('@font-face' + b).split('}')[0] + '}';
    block = block.replace(/url\(https:[^)]+\.woff2\)/, `url(./fonts/${name}_${i}.woff2)`);
    out += block.trim() + "\n";
    i++;
  }
  console.log(name, 'blocks:', i);
}
writeFileSync('assets/fonts.css', out);
console.log('wrote assets/fonts.css', out.length, 'bytes');
